"""``agenteval init`` — scaffold a new project: framework detection, agents.yaml,
a sample golden suite, and a consumer GitHub Actions workflow.

This module only writes files and prints guidance; it never makes a live
provider call itself. ``run_first_evaluation`` is a thin, best-effort wrapper
around the same code path ``agenteval run`` uses, isolated so a missing
dependency or API key degrades to a printed message instead of an exception.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from agenteval.core._fsutil import atomic_write_text

# Ordered so the first matching signature wins when a project depends on more
# than one framework (rare, but deterministic beats alphabetical-random).
_FRAMEWORK_SIGNATURES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("langgraph", ("langgraph", "from langgraph", "import langgraph")),
    ("crewai", ("crewai", "from crewai", "import crewai")),
    ("autogen", ("autogen-agentchat", "autogen_agentchat", "pyautogen", "from autogen")),
    ("openai_agents", ("openai-agents", "from agents import", "import agents\n", "openai_agents")),
)

_ADAPTER_BY_FRAMEWORK: dict[str, str] = {
    "crewai": "agenteval.adapters.crewai:CrewAIAdapter",
    "autogen": "agenteval.adapters.autogen:AutoGenAdapter",
    "openai_agents": "agenteval.adapters.openai_agents:OpenAIAgentsAdapter",
    "langgraph": "agenteval.adapters.langgraph:LangGraphAdapter",
}

_ADAPTER_OPTIONS_BY_FRAMEWORK: dict[str, dict[str, Any]] = {
    "crewai": {
        "crew_import": "my_crew.crew:MyCrew",
        "input_key": "topic",
    },
    "autogen": {
        "agent_import": "my_project.agents:build_research_agent",
    },
    "openai_agents": {
        "agent_import": "my_agents.support:build_support_agent",
    },
    "langgraph": {
        "graph_import": "my_graph.app:build_graph",
    },
}

_EXTRAS_BY_FRAMEWORK: dict[str, str] = {
    "crewai": "crewai",
    "autogen": "autogen",
    "openai_agents": "openai-agents",
    "langgraph": "",
}

_FRAMEWORK_LABELS: dict[str, str] = {
    "crewai": "CrewAI",
    "autogen": "Microsoft AutoGen",
    "openai_agents": "OpenAI Agents SDK",
    "langgraph": "LangGraph",
}

_AGENT_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_MAX_SCAN_FILES = 500


class InitError(ValueError):
    """Raised for invalid ``agenteval init`` input (bad name, bad path, ...)."""


def _read_text_best_effort(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def detect_framework(path: str | Path) -> str | None:
    """Best-effort detection of the agent framework used under ``path``.

    Looks at common dependency manifests first (cheap, high-signal), then a
    bounded walk of Python source for import statements. Returns ``None``
    when nothing matches rather than raising — an undetected framework is an
    expected, gracefully handled outcome, not an error.
    """
    root = Path(path)
    if not root.is_dir():
        return None

    manifest_text = ""
    for name in ("requirements.txt", "requirements-dev.txt", "pyproject.toml", "setup.py", "setup.cfg"):
        manifest_text += "\n" + _read_text_best_effort(root / name)
    manifest_lower = manifest_text.lower()
    for framework, signatures in _FRAMEWORK_SIGNATURES:
        if any(signature in manifest_lower for signature in signatures):
            return framework

    scanned = 0
    for py_file in root.rglob("*.py"):
        # Cap on files *visited*, not just files whose content gets read --
        # otherwise a huge skipped tree (node_modules, .venv, ...) filled with
        # .py-matching paths would never trip this cap and the scan would
        # effectively be unbounded on large projects.
        if scanned >= _MAX_SCAN_FILES:
            break
        scanned += 1
        parts = set(py_file.parts)
        if parts & {".venv", "venv", "node_modules", "site-packages", "__pycache__", ".git"}:
            continue
        text = _read_text_best_effort(py_file)
        text_lower = text.lower()
        for framework, signatures in _FRAMEWORK_SIGNATURES:
            if any(signature in text_lower for signature in signatures):
                return framework
    return None


def _validate_agent_name(name: str) -> str:
    if not _AGENT_NAME_RE.fullmatch(name):
        raise InitError(
            f"Invalid agent name {name!r}; use lowercase letters, digits and underscores, "
            "starting with a letter"
        )
    return name


def _yaml_scalar(value: str) -> str:
    """Render a plain string as a safe single-quoted YAML scalar."""
    return "'" + value.replace("'", "''") + "'"


@dataclass(frozen=True)
class InitPlan:
    """Resolved, framework-aware paths and content generated by ``init``."""

    agent_name: str
    framework: str | None
    agents_yaml_path: Path
    golden_suite_path: Path
    workflow_path: Path


def generate_agents_yaml(
    target_dir: str | Path,
    agent_name: str,
    framework: str | None,
    *,
    force: bool = False,
) -> Path:
    """Write a schema-valid ``agents.yaml`` for one newly scaffolded agent.

    Known frameworks reference their first-party adapter with placeholder
    ``adapter_options`` the user must fill in. An undetected framework falls
    back to the base ``AgentAdapter`` contract class directly — it imports
    cleanly (so the registry still loads), but is disabled by default since
    it cannot be instantiated until the user subclasses it.
    """
    _validate_agent_name(agent_name)
    root = Path(target_dir)
    out_path = root / "agents.yaml"
    if out_path.exists() and not force:
        raise InitError(f"{out_path} already exists (use --force to overwrite)")

    adapter = _ADAPTER_BY_FRAMEWORK.get(framework or "", "agenteval.adapters.base:AgentAdapter")
    options = _ADAPTER_OPTIONS_BY_FRAMEWORK.get(framework or "", {})
    enabled = framework is not None
    env_var = f"{agent_name.upper()}_PATH"

    lines = [
        "version: 1",
        "",
        "agents:",
        f"  {agent_name}:",
        f"    display_name: {_yaml_scalar(agent_name.replace('_', ' ').title())}",
        f"    enabled: {'true' if enabled else 'false'}",
        f"    adapter: {adapter}",
        "    repository:",
        f"      env_var: {env_var}",
        "      default_path: .",
        "      required_paths: []",
        f"    golden_suite: tests/golden/{agent_name}.yaml",
        f"    baseline: baselines/{agent_name}.json",
        "    runs_dir: runs",
    ]
    if options:
        lines.append("    # Placeholder module.path:Name values below — point them at your")
        lines.append("    # own code before running `agenteval run --agent " + agent_name + "`.")
        lines.append("    adapter_options:")
        for key, value in options.items():
            lines.append(f"      {key}: {_yaml_scalar(str(value))}")
    else:
        lines.append("    adapter_options: {}")
    lines.extend(
        [
            "    gates:",
            "      max_correctness_drop: 0.05",
            "      max_hallucination_rate: 0.10",
            "      min_tool_accuracy: 0.90",
            "      fail_on_evaluator_error: true",
            "      fail_on_agent_error: true",
            "    smoke_case_ids: []",
            "",
        ]
    )
    if not enabled:
        lines.insert(
            3,
            "  # No supported framework was detected automatically. Replace 'adapter' below\n"
            "  # with a module.path:ClassName that subclasses agenteval.adapters.base.AgentAdapter,\n"
            "  # then flip 'enabled' to true.",
        )
    atomic_write_text(out_path, "\n".join(lines))
    return out_path


_SAMPLE_CASES_TEMPLATE = """\
# Sample golden suite generated by `agenteval init`.
# Replace prompts and ground_truth with real expectations for your agent,
# then add more cases. See the README's "Golden case example" section for
# the full expects schema (must_call_tools, expected_trajectory, ...).

- id: sample_exact_answer
  prompt: "What is 2 + 2?"
  expects:
    correctness_type: exact
    ground_truth: "4"
  tags: [sample]

- id: sample_numeric_answer
  prompt: "How many days are in a week?"
  expects:
    correctness_type: numeric
    ground_truth: 7
    numeric_tolerance: 0
  tags: [sample]

- id: sample_contains_answer
  prompt: "Name a primary color."
  expects:
    correctness_type: contains
    ground_truth: "red"
  tags: [sample]
"""


def generate_sample_golden_suite(
    target_dir: str | Path,
    agent_name: str,
    *,
    force: bool = False,
) -> Path:
    """Write a small, loadable sample golden suite at ``tests/golden/<agent_name>.yaml``."""
    _validate_agent_name(agent_name)
    out_path = Path(target_dir) / "tests" / "golden" / f"{agent_name}.yaml"
    if out_path.exists() and not force:
        raise InitError(f"{out_path} already exists (use --force to overwrite)")
    atomic_write_text(out_path, _SAMPLE_CASES_TEMPLATE)
    return out_path


def _workflow_template(agent_name: str, framework: str | None) -> str:
    extras = _EXTRAS_BY_FRAMEWORK.get(framework or "", "")
    extras_line = f"          install-extras: {extras}\n" if extras else ""
    return f"""\
name: AgentEval

on:
  pull_request:

permissions:
  contents: read

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # GitHub Actions resolve owner/repository@ref. AgentEval publishes its
      # reusable composite action as nishanttyagi28/agenteval@v1.
      - name: Run AgentEval
        id: agenteval
        uses: nishanttyagi28/agenteval@v1
        with:
          agent: {agent_name}
          config-file: agents.yaml
          agent-path: .
          cases-file: tests/golden/{agent_name}.yaml
          runs-dir: .agenteval/runs
{extras_line}          no-llm-judge: "true"

      - name: Upload AgentEval report
        if: always() && steps.agenteval.outputs.report-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: agenteval-report
          path: |
            ${{{{ steps.agenteval.outputs.report-path }}}}
            ${{{{ steps.agenteval.outputs.comparison-path }}}}
"""


def generate_github_workflow(
    target_dir: str | Path,
    agent_name: str,
    framework: str | None,
    *,
    force: bool = False,
) -> Path:
    """Write ``.github/workflows/agenteval.yml`` consuming the reusable composite action."""
    _validate_agent_name(agent_name)
    out_path = Path(target_dir) / ".github" / "workflows" / "agenteval.yml"
    if out_path.exists() and not force:
        raise InitError(f"{out_path} already exists (use --force to overwrite)")
    atomic_write_text(out_path, _workflow_template(agent_name, framework))
    return out_path


def scaffold_project(
    target_dir: str | Path,
    agent_name: str,
    *,
    framework: str | None = "auto",
    force: bool = False,
) -> InitPlan:
    """Detect (if requested) and write all three scaffold files. Pure I/O, no live calls.

    ``framework="auto"`` (the default) runs :func:`detect_framework`. Passing
    ``None`` explicitly means "no framework" (scaffold the disabled generic
    placeholder) without attempting detection.
    """
    _validate_agent_name(agent_name)
    root = Path(target_dir)
    resolved_framework = detect_framework(root) if framework == "auto" else framework
    if resolved_framework not in (None, *_ADAPTER_BY_FRAMEWORK):
        raise InitError(
            f"Unknown framework {resolved_framework!r}; expected one of "
            f"auto, {', '.join(_ADAPTER_BY_FRAMEWORK)}, or none"
        )

    agents_yaml_path = generate_agents_yaml(root, agent_name, resolved_framework, force=force)
    golden_suite_path = generate_sample_golden_suite(root, agent_name, force=force)
    workflow_path = generate_github_workflow(root, agent_name, resolved_framework, force=force)
    return InitPlan(
        agent_name=agent_name,
        framework=resolved_framework,
        agents_yaml_path=agents_yaml_path,
        golden_suite_path=golden_suite_path,
        workflow_path=workflow_path,
    )


def run_first_evaluation(
    target_dir: str | Path,
    agent_name: str,
    *,
    quiet: bool = False,
) -> int | None:
    """Best-effort first `agenteval run` against the freshly scaffolded registry.

    Returns the process-style exit code (0 success, non-zero failure) or
    ``None`` when the run could not even be attempted (e.g. the scaffolded
    adapter has no real implementation yet). Never raises — a failed or
    skipped first run is expected for a scaffold and must not abort ``init``.
    """
    from agenteval.core.config import AgentDependencyNotFound
    from agenteval.core.registry import load_agent_registry

    registry_path = Path(target_dir) / "agents.yaml"
    try:
        registry = load_agent_registry(registry_path)
        config = registry[agent_name]
    except (OSError, ValueError, KeyError) as exc:
        print(f"first-run skipped: could not load registry: {exc}")
        return None
    if not config.enabled:
        print(
            "first-run skipped: no supported framework was detected, so the "
            f"'{agent_name}' entry in agents.yaml is disabled. Implement your "
            "adapter, enable the entry, then run `agenteval run` yourself."
        )
        return None

    from agenteval.cli import _run_registered_agent, build_parser

    argv = ["run", "--agent", agent_name, "--registry", str(registry_path)]
    if quiet:
        argv.append("--quiet")
    args = build_parser().parse_args(argv)
    try:
        result = _run_registered_agent(args, config, registry_path)
    except AgentDependencyNotFound as exc:
        print(f"first-run skipped: agent dependency not found: {exc}")
        return None
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"first-run failed: {exc}")
        return 1
    return 0 if result["errors"] == 0 else 1


def next_steps_message(plan: InitPlan) -> str:
    """Human-readable guidance printed after a successful scaffold."""
    framework_label = _FRAMEWORK_LABELS.get(plan.framework or "", None)
    lines = ["", "AgentEval scaffold created:", f"  {plan.agents_yaml_path}", f"  {plan.golden_suite_path}", f"  {plan.workflow_path}", ""]
    if framework_label:
        lines.append(f"Detected framework: {framework_label}")
        lines.append(
            f"Next: fill in the adapter_options placeholder values for '{plan.agent_name}' "
            "in agents.yaml (see the comment above that block), then run:"
        )
        lines.append(f"  agenteval run --agent {plan.agent_name}")
    else:
        lines.append("No supported framework was auto-detected (CrewAI, LangGraph, AutoGen, OpenAI Agents SDK).")
        lines.append(
            f"Next: subclass agenteval.adapters.base.AgentAdapter for '{plan.agent_name}', point "
            "'adapter' in agents.yaml at it, set enabled: true, then run:"
        )
        lines.append(f"  agenteval run --agent {plan.agent_name}")
    lines.append("")
    lines.append(f"Edit {plan.golden_suite_path} with real prompts and expectations for your agent.")
    lines.append(
        f"Commit {plan.workflow_path} to get PR-triggered regression checks once a GROQ_API_KEY "
        "(or your provider's key) secret is configured."
    )
    return "\n".join(lines)
